/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminAuditLogsIndexRouteImport } from './routes/_admin/audit-logs/index'
import { Route as AdminBoatsIndexRouteImport } from './routes/_admin/boats/index'
import { Route as AdminBoatsCreateRouteImport } from './routes/_admin/boats/create'
import { Route as AdminBookingChangesIndexRouteImport } from './routes/_admin/booking-changes/index'
import { Route as AdminBookingsIndexRouteImport } from './routes/_admin/bookings/index'
import { Route as AdminBookingsCreateRouteImport } from './routes/_admin/bookings/create'
import { Route as AdminCheckInIndexRouteImport } from './routes/_admin/check-in/index'
import { Route as AdminCouponsIndexRouteImport } from './routes/_admin/coupons/index'
import { Route as AdminCouponsCreateRouteImport } from './routes/_admin/coupons/create'
import { Route as AdminInvoicesIndexRouteImport } from './routes/_admin/invoices/index'
import { Route as AdminJourneysIndexRouteImport } from './routes/_admin/journeys/index'
import { Route as AdminJourneysCreateRouteImport } from './routes/_admin/journeys/create'
import { Route as AdminLocationsIndexRouteImport } from './routes/_admin/locations/index'
import { Route as AdminLocationsCreateRouteImport } from './routes/_admin/locations/create'
import { Route as AdminPaymentsIndexRouteImport } from './routes/_admin/payments/index'
import { Route as AdminPostsIndexRouteImport } from './routes/_admin/posts/index'
import { Route as AdminRolesIndexRouteImport } from './routes/_admin/roles/index'
import { Route as AdminRolesCreateRouteImport } from './routes/_admin/roles/create'
import { Route as AdminSchedulesIndexRouteImport } from './routes/_admin/schedules/index'
import { Route as AdminSchedulesCreateRouteImport } from './routes/_admin/schedules/create'
import { Route as AdminSeatClassesIndexRouteImport } from './routes/_admin/seat-classes/index'
import { Route as AdminSeatClassesCreateRouteImport } from './routes/_admin/seat-classes/create'
import { Route as AdminSeatMapsIndexRouteImport } from './routes/_admin/seat-maps/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/_admin/settings/index'
import { Route as AdminTravelerTypesIndexRouteImport } from './routes/_admin/traveler-types/index'
import { Route as AdminTravelerTypesCreateRouteImport } from './routes/_admin/traveler-types/create'
import { Route as AdminTripsIndexRouteImport } from './routes/_admin/trips/index'
import { Route as AdminTripsCreateRouteImport } from './routes/_admin/trips/create'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users/index'
import { Route as AdminUsersCreateRouteImport } from './routes/_admin/users/create'
import { Route as AdminBoatsBoatIdEditRouteImport } from './routes/_admin/boats/$boatId.edit'
import { Route as AdminBookingsBookingIdEditRouteImport } from './routes/_admin/bookings/$bookingId.edit'
import { Route as AdminCouponsCouponIdEditRouteImport } from './routes/_admin/coupons/$couponId.edit'
import { Route as AdminJourneysJourneyIdEditRouteImport } from './routes/_admin/journeys/$journeyId.edit'
import { Route as AdminLocationsLocationIdEditRouteImport } from './routes/_admin/locations/$locationId.edit'
import { Route as AdminRolesRoleIdEditRouteImport } from './routes/_admin/roles/$roleId.edit'
import { Route as AdminSchedulesScheduleIdEditRouteImport } from './routes/_admin/schedules/$scheduleId.edit'
import { Route as AdminSeatClassesClassIdEditRouteImport } from './routes/_admin/seat-classes/$classId.edit'
import { Route as AdminTravelerTypesTypeIdEditRouteImport } from './routes/_admin/traveler-types/$typeId.edit'
import { Route as AdminTripsTripIdEditRouteImport } from './routes/_admin/trips/$tripId.edit'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/_admin/users/$userId.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsIndexRoute = AdminAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoatsIndexRoute = AdminBoatsIndexRouteImport.update({
  id: '/boats/',
  path: '/boats/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoatsCreateRoute = AdminBoatsCreateRouteImport.update({
  id: '/boats/create',
  path: '/boats/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingChangesIndexRoute =
  AdminBookingChangesIndexRouteImport.update({
    id: '/booking-changes/',
    path: '/booking-changes/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsCreateRoute = AdminBookingsCreateRouteImport.update({
  id: '/bookings/create',
  path: '/bookings/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckInIndexRoute = AdminCheckInIndexRouteImport.update({
  id: '/check-in/',
  path: '/check-in/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsIndexRoute = AdminCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsCreateRoute = AdminCouponsCreateRouteImport.update({
  id: '/coupons/create',
  path: '/coupons/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesIndexRoute = AdminInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJourneysIndexRoute = AdminJourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJourneysCreateRoute = AdminJourneysCreateRouteImport.update({
  id: '/journeys/create',
  path: '/journeys/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsIndexRoute = AdminLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsCreateRoute = AdminLocationsCreateRouteImport.update({
  id: '/locations/create',
  path: '/locations/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesCreateRoute = AdminRolesCreateRouteImport.update({
  id: '/roles/create',
  path: '/roles/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesIndexRoute = AdminSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesCreateRoute = AdminSchedulesCreateRouteImport.update({
  id: '/schedules/create',
  path: '/schedules/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeatClassesIndexRoute = AdminSeatClassesIndexRouteImport.update({
  id: '/seat-classes/',
  path: '/seat-classes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeatClassesCreateRoute = AdminSeatClassesCreateRouteImport.update({
  id: '/seat-classes/create',
  path: '/seat-classes/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeatMapsIndexRoute = AdminSeatMapsIndexRouteImport.update({
  id: '/seat-maps/',
  path: '/seat-maps/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTravelerTypesIndexRoute = AdminTravelerTypesIndexRouteImport.update({
  id: '/traveler-types/',
  path: '/traveler-types/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTravelerTypesCreateRoute =
  AdminTravelerTypesCreateRouteImport.update({
    id: '/traveler-types/create',
    path: '/traveler-types/create',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTripsIndexRoute = AdminTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsCreateRoute = AdminTripsCreateRouteImport.update({
  id: '/trips/create',
  path: '/trips/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersCreateRoute = AdminUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoatsBoatIdEditRoute = AdminBoatsBoatIdEditRouteImport.update({
  id: '/boats/$boatId/edit',
  path: '/boats/$boatId/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsBookingIdEditRoute =
  AdminBookingsBookingIdEditRouteImport.update({
    id: '/bookings/$bookingId/edit',
    path: '/bookings/$bookingId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCouponsCouponIdEditRoute =
  AdminCouponsCouponIdEditRouteImport.update({
    id: '/coupons/$couponId/edit',
    path: '/coupons/$couponId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminJourneysJourneyIdEditRoute =
  AdminJourneysJourneyIdEditRouteImport.update({
    id: '/journeys/$journeyId/edit',
    path: '/journeys/$journeyId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLocationsLocationIdEditRoute =
  AdminLocationsLocationIdEditRouteImport.update({
    id: '/locations/$locationId/edit',
    path: '/locations/$locationId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRolesRoleIdEditRoute = AdminRolesRoleIdEditRouteImport.update({
  id: '/roles/$roleId/edit',
  path: '/roles/$roleId/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesScheduleIdEditRoute =
  AdminSchedulesScheduleIdEditRouteImport.update({
    id: '/schedules/$scheduleId/edit',
    path: '/schedules/$scheduleId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSeatClassesClassIdEditRoute =
  AdminSeatClassesClassIdEditRouteImport.update({
    id: '/seat-classes/$classId/edit',
    path: '/seat-classes/$classId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTravelerTypesTypeIdEditRoute =
  AdminTravelerTypesTypeIdEditRouteImport.update({
    id: '/traveler-types/$typeId/edit',
    path: '/traveler-types/$typeId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTripsTripIdEditRoute = AdminTripsTripIdEditRouteImport.update({
  id: '/trips/$tripId/edit',
  path: '/trips/$tripId/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/boats/create': typeof AdminBoatsCreateRoute
  '/bookings/create': typeof AdminBookingsCreateRoute
  '/coupons/create': typeof AdminCouponsCreateRoute
  '/journeys/create': typeof AdminJourneysCreateRoute
  '/locations/create': typeof AdminLocationsCreateRoute
  '/roles/create': typeof AdminRolesCreateRoute
  '/schedules/create': typeof AdminSchedulesCreateRoute
  '/seat-classes/create': typeof AdminSeatClassesCreateRoute
  '/traveler-types/create': typeof AdminTravelerTypesCreateRoute
  '/trips/create': typeof AdminTripsCreateRoute
  '/users/create': typeof AdminUsersCreateRoute
  '/audit-logs/': typeof AdminAuditLogsIndexRoute
  '/boats/': typeof AdminBoatsIndexRoute
  '/booking-changes/': typeof AdminBookingChangesIndexRoute
  '/bookings/': typeof AdminBookingsIndexRoute
  '/check-in/': typeof AdminCheckInIndexRoute
  '/coupons/': typeof AdminCouponsIndexRoute
  '/invoices/': typeof AdminInvoicesIndexRoute
  '/journeys/': typeof AdminJourneysIndexRoute
  '/locations/': typeof AdminLocationsIndexRoute
  '/payments/': typeof AdminPaymentsIndexRoute
  '/posts/': typeof AdminPostsIndexRoute
  '/roles/': typeof AdminRolesIndexRoute
  '/schedules/': typeof AdminSchedulesIndexRoute
  '/seat-classes/': typeof AdminSeatClassesIndexRoute
  '/seat-maps/': typeof AdminSeatMapsIndexRoute
  '/settings/': typeof AdminSettingsIndexRoute
  '/traveler-types/': typeof AdminTravelerTypesIndexRoute
  '/trips/': typeof AdminTripsIndexRoute
  '/users/': typeof AdminUsersIndexRoute
  '/boats/$boatId/edit': typeof AdminBoatsBoatIdEditRoute
  '/bookings/$bookingId/edit': typeof AdminBookingsBookingIdEditRoute
  '/coupons/$couponId/edit': typeof AdminCouponsCouponIdEditRoute
  '/journeys/$journeyId/edit': typeof AdminJourneysJourneyIdEditRoute
  '/locations/$locationId/edit': typeof AdminLocationsLocationIdEditRoute
  '/roles/$roleId/edit': typeof AdminRolesRoleIdEditRoute
  '/schedules/$scheduleId/edit': typeof AdminSchedulesScheduleIdEditRoute
  '/seat-classes/$classId/edit': typeof AdminSeatClassesClassIdEditRoute
  '/traveler-types/$typeId/edit': typeof AdminTravelerTypesTypeIdEditRoute
  '/trips/$tripId/edit': typeof AdminTripsTripIdEditRoute
  '/users/$userId/edit': typeof AdminUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AdminIndexRoute
  '/boats/create': typeof AdminBoatsCreateRoute
  '/bookings/create': typeof AdminBookingsCreateRoute
  '/coupons/create': typeof AdminCouponsCreateRoute
  '/journeys/create': typeof AdminJourneysCreateRoute
  '/locations/create': typeof AdminLocationsCreateRoute
  '/roles/create': typeof AdminRolesCreateRoute
  '/schedules/create': typeof AdminSchedulesCreateRoute
  '/seat-classes/create': typeof AdminSeatClassesCreateRoute
  '/traveler-types/create': typeof AdminTravelerTypesCreateRoute
  '/trips/create': typeof AdminTripsCreateRoute
  '/users/create': typeof AdminUsersCreateRoute
  '/audit-logs': typeof AdminAuditLogsIndexRoute
  '/boats': typeof AdminBoatsIndexRoute
  '/booking-changes': typeof AdminBookingChangesIndexRoute
  '/bookings': typeof AdminBookingsIndexRoute
  '/check-in': typeof AdminCheckInIndexRoute
  '/coupons': typeof AdminCouponsIndexRoute
  '/invoices': typeof AdminInvoicesIndexRoute
  '/journeys': typeof AdminJourneysIndexRoute
  '/locations': typeof AdminLocationsIndexRoute
  '/payments': typeof AdminPaymentsIndexRoute
  '/posts': typeof AdminPostsIndexRoute
  '/roles': typeof AdminRolesIndexRoute
  '/schedules': typeof AdminSchedulesIndexRoute
  '/seat-classes': typeof AdminSeatClassesIndexRoute
  '/seat-maps': typeof AdminSeatMapsIndexRoute
  '/settings': typeof AdminSettingsIndexRoute
  '/traveler-types': typeof AdminTravelerTypesIndexRoute
  '/trips': typeof AdminTripsIndexRoute
  '/users': typeof AdminUsersIndexRoute
  '/boats/$boatId/edit': typeof AdminBoatsBoatIdEditRoute
  '/bookings/$bookingId/edit': typeof AdminBookingsBookingIdEditRoute
  '/coupons/$couponId/edit': typeof AdminCouponsCouponIdEditRoute
  '/journeys/$journeyId/edit': typeof AdminJourneysJourneyIdEditRoute
  '/locations/$locationId/edit': typeof AdminLocationsLocationIdEditRoute
  '/roles/$roleId/edit': typeof AdminRolesRoleIdEditRoute
  '/schedules/$scheduleId/edit': typeof AdminSchedulesScheduleIdEditRoute
  '/seat-classes/$classId/edit': typeof AdminSeatClassesClassIdEditRoute
  '/traveler-types/$typeId/edit': typeof AdminTravelerTypesTypeIdEditRoute
  '/trips/$tripId/edit': typeof AdminTripsTripIdEditRoute
  '/users/$userId/edit': typeof AdminUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/boats/create': typeof AdminBoatsCreateRoute
  '/_admin/bookings/create': typeof AdminBookingsCreateRoute
  '/_admin/coupons/create': typeof AdminCouponsCreateRoute
  '/_admin/journeys/create': typeof AdminJourneysCreateRoute
  '/_admin/locations/create': typeof AdminLocationsCreateRoute
  '/_admin/roles/create': typeof AdminRolesCreateRoute
  '/_admin/schedules/create': typeof AdminSchedulesCreateRoute
  '/_admin/seat-classes/create': typeof AdminSeatClassesCreateRoute
  '/_admin/traveler-types/create': typeof AdminTravelerTypesCreateRoute
  '/_admin/trips/create': typeof AdminTripsCreateRoute
  '/_admin/users/create': typeof AdminUsersCreateRoute
  '/_admin/audit-logs/': typeof AdminAuditLogsIndexRoute
  '/_admin/boats/': typeof AdminBoatsIndexRoute
  '/_admin/booking-changes/': typeof AdminBookingChangesIndexRoute
  '/_admin/bookings/': typeof AdminBookingsIndexRoute
  '/_admin/check-in/': typeof AdminCheckInIndexRoute
  '/_admin/coupons/': typeof AdminCouponsIndexRoute
  '/_admin/invoices/': typeof AdminInvoicesIndexRoute
  '/_admin/journeys/': typeof AdminJourneysIndexRoute
  '/_admin/locations/': typeof AdminLocationsIndexRoute
  '/_admin/payments/': typeof AdminPaymentsIndexRoute
  '/_admin/posts/': typeof AdminPostsIndexRoute
  '/_admin/roles/': typeof AdminRolesIndexRoute
  '/_admin/schedules/': typeof AdminSchedulesIndexRoute
  '/_admin/seat-classes/': typeof AdminSeatClassesIndexRoute
  '/_admin/seat-maps/': typeof AdminSeatMapsIndexRoute
  '/_admin/settings/': typeof AdminSettingsIndexRoute
  '/_admin/traveler-types/': typeof AdminTravelerTypesIndexRoute
  '/_admin/trips/': typeof AdminTripsIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
  '/_admin/boats/$boatId/edit': typeof AdminBoatsBoatIdEditRoute
  '/_admin/bookings/$bookingId/edit': typeof AdminBookingsBookingIdEditRoute
  '/_admin/coupons/$couponId/edit': typeof AdminCouponsCouponIdEditRoute
  '/_admin/journeys/$journeyId/edit': typeof AdminJourneysJourneyIdEditRoute
  '/_admin/locations/$locationId/edit': typeof AdminLocationsLocationIdEditRoute
  '/_admin/roles/$roleId/edit': typeof AdminRolesRoleIdEditRoute
  '/_admin/schedules/$scheduleId/edit': typeof AdminSchedulesScheduleIdEditRoute
  '/_admin/seat-classes/$classId/edit': typeof AdminSeatClassesClassIdEditRoute
  '/_admin/traveler-types/$typeId/edit': typeof AdminTravelerTypesTypeIdEditRoute
  '/_admin/trips/$tripId/edit': typeof AdminTripsTripIdEditRoute
  '/_admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/boats/create'
    | '/bookings/create'
    | '/coupons/create'
    | '/journeys/create'
    | '/locations/create'
    | '/roles/create'
    | '/schedules/create'
    | '/seat-classes/create'
    | '/traveler-types/create'
    | '/trips/create'
    | '/users/create'
    | '/audit-logs/'
    | '/boats/'
    | '/booking-changes/'
    | '/bookings/'
    | '/check-in/'
    | '/coupons/'
    | '/invoices/'
    | '/journeys/'
    | '/locations/'
    | '/payments/'
    | '/posts/'
    | '/roles/'
    | '/schedules/'
    | '/seat-classes/'
    | '/seat-maps/'
    | '/settings/'
    | '/traveler-types/'
    | '/trips/'
    | '/users/'
    | '/boats/$boatId/edit'
    | '/bookings/$bookingId/edit'
    | '/coupons/$couponId/edit'
    | '/journeys/$journeyId/edit'
    | '/locations/$locationId/edit'
    | '/roles/$roleId/edit'
    | '/schedules/$scheduleId/edit'
    | '/seat-classes/$classId/edit'
    | '/traveler-types/$typeId/edit'
    | '/trips/$tripId/edit'
    | '/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/boats/create'
    | '/bookings/create'
    | '/coupons/create'
    | '/journeys/create'
    | '/locations/create'
    | '/roles/create'
    | '/schedules/create'
    | '/seat-classes/create'
    | '/traveler-types/create'
    | '/trips/create'
    | '/users/create'
    | '/audit-logs'
    | '/boats'
    | '/booking-changes'
    | '/bookings'
    | '/check-in'
    | '/coupons'
    | '/invoices'
    | '/journeys'
    | '/locations'
    | '/payments'
    | '/posts'
    | '/roles'
    | '/schedules'
    | '/seat-classes'
    | '/seat-maps'
    | '/settings'
    | '/traveler-types'
    | '/trips'
    | '/users'
    | '/boats/$boatId/edit'
    | '/bookings/$bookingId/edit'
    | '/coupons/$couponId/edit'
    | '/journeys/$journeyId/edit'
    | '/locations/$locationId/edit'
    | '/roles/$roleId/edit'
    | '/schedules/$scheduleId/edit'
    | '/seat-classes/$classId/edit'
    | '/traveler-types/$typeId/edit'
    | '/trips/$tripId/edit'
    | '/users/$userId/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/'
    | '/_admin/boats/create'
    | '/_admin/bookings/create'
    | '/_admin/coupons/create'
    | '/_admin/journeys/create'
    | '/_admin/locations/create'
    | '/_admin/roles/create'
    | '/_admin/schedules/create'
    | '/_admin/seat-classes/create'
    | '/_admin/traveler-types/create'
    | '/_admin/trips/create'
    | '/_admin/users/create'
    | '/_admin/audit-logs/'
    | '/_admin/boats/'
    | '/_admin/booking-changes/'
    | '/_admin/bookings/'
    | '/_admin/check-in/'
    | '/_admin/coupons/'
    | '/_admin/invoices/'
    | '/_admin/journeys/'
    | '/_admin/locations/'
    | '/_admin/payments/'
    | '/_admin/posts/'
    | '/_admin/roles/'
    | '/_admin/schedules/'
    | '/_admin/seat-classes/'
    | '/_admin/seat-maps/'
    | '/_admin/settings/'
    | '/_admin/traveler-types/'
    | '/_admin/trips/'
    | '/_admin/users/'
    | '/_admin/boats/$boatId/edit'
    | '/_admin/bookings/$bookingId/edit'
    | '/_admin/coupons/$couponId/edit'
    | '/_admin/journeys/$journeyId/edit'
    | '/_admin/locations/$locationId/edit'
    | '/_admin/roles/$roleId/edit'
    | '/_admin/schedules/$scheduleId/edit'
    | '/_admin/seat-classes/$classId/edit'
    | '/_admin/traveler-types/$typeId/edit'
    | '/_admin/trips/$tripId/edit'
    | '/_admin/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit-logs/': {
      id: '/_admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AdminAuditLogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/boats/': {
      id: '/_admin/boats/'
      path: '/boats'
      fullPath: '/boats/'
      preLoaderRoute: typeof AdminBoatsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/boats/create': {
      id: '/_admin/boats/create'
      path: '/boats/create'
      fullPath: '/boats/create'
      preLoaderRoute: typeof AdminBoatsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/booking-changes/': {
      id: '/_admin/booking-changes/'
      path: '/booking-changes'
      fullPath: '/booking-changes/'
      preLoaderRoute: typeof AdminBookingChangesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bookings/': {
      id: '/_admin/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bookings/create': {
      id: '/_admin/bookings/create'
      path: '/bookings/create'
      fullPath: '/bookings/create'
      preLoaderRoute: typeof AdminBookingsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/check-in/': {
      id: '/_admin/check-in/'
      path: '/check-in'
      fullPath: '/check-in/'
      preLoaderRoute: typeof AdminCheckInIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/coupons/': {
      id: '/_admin/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof AdminCouponsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/coupons/create': {
      id: '/_admin/coupons/create'
      path: '/coupons/create'
      fullPath: '/coupons/create'
      preLoaderRoute: typeof AdminCouponsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/invoices/': {
      id: '/_admin/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AdminInvoicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/journeys/': {
      id: '/_admin/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof AdminJourneysIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/journeys/create': {
      id: '/_admin/journeys/create'
      path: '/journeys/create'
      fullPath: '/journeys/create'
      preLoaderRoute: typeof AdminJourneysCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locations/': {
      id: '/_admin/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AdminLocationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locations/create': {
      id: '/_admin/locations/create'
      path: '/locations/create'
      fullPath: '/locations/create'
      preLoaderRoute: typeof AdminLocationsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payments/': {
      id: '/_admin/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/posts/': {
      id: '/_admin/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles/': {
      id: '/_admin/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles/create': {
      id: '/_admin/roles/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof AdminRolesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/schedules/': {
      id: '/_admin/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof AdminSchedulesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/schedules/create': {
      id: '/_admin/schedules/create'
      path: '/schedules/create'
      fullPath: '/schedules/create'
      preLoaderRoute: typeof AdminSchedulesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seat-classes/': {
      id: '/_admin/seat-classes/'
      path: '/seat-classes'
      fullPath: '/seat-classes/'
      preLoaderRoute: typeof AdminSeatClassesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seat-classes/create': {
      id: '/_admin/seat-classes/create'
      path: '/seat-classes/create'
      fullPath: '/seat-classes/create'
      preLoaderRoute: typeof AdminSeatClassesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seat-maps/': {
      id: '/_admin/seat-maps/'
      path: '/seat-maps'
      fullPath: '/seat-maps/'
      preLoaderRoute: typeof AdminSeatMapsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/': {
      id: '/_admin/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/traveler-types/': {
      id: '/_admin/traveler-types/'
      path: '/traveler-types'
      fullPath: '/traveler-types/'
      preLoaderRoute: typeof AdminTravelerTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/traveler-types/create': {
      id: '/_admin/traveler-types/create'
      path: '/traveler-types/create'
      fullPath: '/traveler-types/create'
      preLoaderRoute: typeof AdminTravelerTypesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/trips/': {
      id: '/_admin/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AdminTripsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/trips/create': {
      id: '/_admin/trips/create'
      path: '/trips/create'
      fullPath: '/trips/create'
      preLoaderRoute: typeof AdminTripsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/create': {
      id: '/_admin/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AdminUsersCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/boats/$boatId/edit': {
      id: '/_admin/boats/$boatId/edit'
      path: '/boats/$boatId/edit'
      fullPath: '/boats/$boatId/edit'
      preLoaderRoute: typeof AdminBoatsBoatIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bookings/$bookingId/edit': {
      id: '/_admin/bookings/$bookingId/edit'
      path: '/bookings/$bookingId/edit'
      fullPath: '/bookings/$bookingId/edit'
      preLoaderRoute: typeof AdminBookingsBookingIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/coupons/$couponId/edit': {
      id: '/_admin/coupons/$couponId/edit'
      path: '/coupons/$couponId/edit'
      fullPath: '/coupons/$couponId/edit'
      preLoaderRoute: typeof AdminCouponsCouponIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/journeys/$journeyId/edit': {
      id: '/_admin/journeys/$journeyId/edit'
      path: '/journeys/$journeyId/edit'
      fullPath: '/journeys/$journeyId/edit'
      preLoaderRoute: typeof AdminJourneysJourneyIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locations/$locationId/edit': {
      id: '/_admin/locations/$locationId/edit'
      path: '/locations/$locationId/edit'
      fullPath: '/locations/$locationId/edit'
      preLoaderRoute: typeof AdminLocationsLocationIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles/$roleId/edit': {
      id: '/_admin/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/roles/$roleId/edit'
      preLoaderRoute: typeof AdminRolesRoleIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/schedules/$scheduleId/edit': {
      id: '/_admin/schedules/$scheduleId/edit'
      path: '/schedules/$scheduleId/edit'
      fullPath: '/schedules/$scheduleId/edit'
      preLoaderRoute: typeof AdminSchedulesScheduleIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seat-classes/$classId/edit': {
      id: '/_admin/seat-classes/$classId/edit'
      path: '/seat-classes/$classId/edit'
      fullPath: '/seat-classes/$classId/edit'
      preLoaderRoute: typeof AdminSeatClassesClassIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/traveler-types/$typeId/edit': {
      id: '/_admin/traveler-types/$typeId/edit'
      path: '/traveler-types/$typeId/edit'
      fullPath: '/traveler-types/$typeId/edit'
      preLoaderRoute: typeof AdminTravelerTypesTypeIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/trips/$tripId/edit': {
      id: '/_admin/trips/$tripId/edit'
      path: '/trips/$tripId/edit'
      fullPath: '/trips/$tripId/edit'
      preLoaderRoute: typeof AdminTripsTripIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/$userId/edit': {
      id: '/_admin/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBoatsCreateRoute: typeof AdminBoatsCreateRoute
  AdminBookingsCreateRoute: typeof AdminBookingsCreateRoute
  AdminCouponsCreateRoute: typeof AdminCouponsCreateRoute
  AdminJourneysCreateRoute: typeof AdminJourneysCreateRoute
  AdminLocationsCreateRoute: typeof AdminLocationsCreateRoute
  AdminRolesCreateRoute: typeof AdminRolesCreateRoute
  AdminSchedulesCreateRoute: typeof AdminSchedulesCreateRoute
  AdminSeatClassesCreateRoute: typeof AdminSeatClassesCreateRoute
  AdminTravelerTypesCreateRoute: typeof AdminTravelerTypesCreateRoute
  AdminTripsCreateRoute: typeof AdminTripsCreateRoute
  AdminUsersCreateRoute: typeof AdminUsersCreateRoute
  AdminAuditLogsIndexRoute: typeof AdminAuditLogsIndexRoute
  AdminBoatsIndexRoute: typeof AdminBoatsIndexRoute
  AdminBookingChangesIndexRoute: typeof AdminBookingChangesIndexRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminCheckInIndexRoute: typeof AdminCheckInIndexRoute
  AdminCouponsIndexRoute: typeof AdminCouponsIndexRoute
  AdminInvoicesIndexRoute: typeof AdminInvoicesIndexRoute
  AdminJourneysIndexRoute: typeof AdminJourneysIndexRoute
  AdminLocationsIndexRoute: typeof AdminLocationsIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminSchedulesIndexRoute: typeof AdminSchedulesIndexRoute
  AdminSeatClassesIndexRoute: typeof AdminSeatClassesIndexRoute
  AdminSeatMapsIndexRoute: typeof AdminSeatMapsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTravelerTypesIndexRoute: typeof AdminTravelerTypesIndexRoute
  AdminTripsIndexRoute: typeof AdminTripsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminBoatsBoatIdEditRoute: typeof AdminBoatsBoatIdEditRoute
  AdminBookingsBookingIdEditRoute: typeof AdminBookingsBookingIdEditRoute
  AdminCouponsCouponIdEditRoute: typeof AdminCouponsCouponIdEditRoute
  AdminJourneysJourneyIdEditRoute: typeof AdminJourneysJourneyIdEditRoute
  AdminLocationsLocationIdEditRoute: typeof AdminLocationsLocationIdEditRoute
  AdminRolesRoleIdEditRoute: typeof AdminRolesRoleIdEditRoute
  AdminSchedulesScheduleIdEditRoute: typeof AdminSchedulesScheduleIdEditRoute
  AdminSeatClassesClassIdEditRoute: typeof AdminSeatClassesClassIdEditRoute
  AdminTravelerTypesTypeIdEditRoute: typeof AdminTravelerTypesTypeIdEditRoute
  AdminTripsTripIdEditRoute: typeof AdminTripsTripIdEditRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBoatsCreateRoute: AdminBoatsCreateRoute,
  AdminBookingsCreateRoute: AdminBookingsCreateRoute,
  AdminCouponsCreateRoute: AdminCouponsCreateRoute,
  AdminJourneysCreateRoute: AdminJourneysCreateRoute,
  AdminLocationsCreateRoute: AdminLocationsCreateRoute,
  AdminRolesCreateRoute: AdminRolesCreateRoute,
  AdminSchedulesCreateRoute: AdminSchedulesCreateRoute,
  AdminSeatClassesCreateRoute: AdminSeatClassesCreateRoute,
  AdminTravelerTypesCreateRoute: AdminTravelerTypesCreateRoute,
  AdminTripsCreateRoute: AdminTripsCreateRoute,
  AdminUsersCreateRoute: AdminUsersCreateRoute,
  AdminAuditLogsIndexRoute: AdminAuditLogsIndexRoute,
  AdminBoatsIndexRoute: AdminBoatsIndexRoute,
  AdminBookingChangesIndexRoute: AdminBookingChangesIndexRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminCheckInIndexRoute: AdminCheckInIndexRoute,
  AdminCouponsIndexRoute: AdminCouponsIndexRoute,
  AdminInvoicesIndexRoute: AdminInvoicesIndexRoute,
  AdminJourneysIndexRoute: AdminJourneysIndexRoute,
  AdminLocationsIndexRoute: AdminLocationsIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminSchedulesIndexRoute: AdminSchedulesIndexRoute,
  AdminSeatClassesIndexRoute: AdminSeatClassesIndexRoute,
  AdminSeatMapsIndexRoute: AdminSeatMapsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTravelerTypesIndexRoute: AdminTravelerTypesIndexRoute,
  AdminTripsIndexRoute: AdminTripsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminBoatsBoatIdEditRoute: AdminBoatsBoatIdEditRoute,
  AdminBookingsBookingIdEditRoute: AdminBookingsBookingIdEditRoute,
  AdminCouponsCouponIdEditRoute: AdminCouponsCouponIdEditRoute,
  AdminJourneysJourneyIdEditRoute: AdminJourneysJourneyIdEditRoute,
  AdminLocationsLocationIdEditRoute: AdminLocationsLocationIdEditRoute,
  AdminRolesRoleIdEditRoute: AdminRolesRoleIdEditRoute,
  AdminSchedulesScheduleIdEditRoute: AdminSchedulesScheduleIdEditRoute,
  AdminSeatClassesClassIdEditRoute: AdminSeatClassesClassIdEditRoute,
  AdminTravelerTypesTypeIdEditRoute: AdminTravelerTypesTypeIdEditRoute,
  AdminTripsTripIdEditRoute: AdminTripsTripIdEditRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
